namespace PDEventStore.Store.Persistence
{
    using System;

    public class EventRecord
    {
        /// <summary>
        /// Gets or sets StoreRecord sequence. Generated by storage (read-only)
        /// </summary>
        /// <value>
        /// The sequence.
        /// </value>
        public int Sequence { get; set; }
        /// <summary>
        /// Gets or sets the Store Record timestamp.
        /// </summary>
        /// <value>
        /// The timestamp.
        /// </value>
        public DateTimeOffset Timestamp { get; set; }

        public string BucketId { get; set; }
        public Guid CommitId { get; set; }
        /// <summary>
        /// Gets or sets the process identifier.
        /// Used to restore ProcessManager states.
        /// </summary>
        /// <value>
        /// The process identifier.
        /// </value>
        public Guid ProcessId { get; set; }

        public Guid AggregateId { get; set; }
        public string AggregateTypeName { get; set; }
        public Guid AggregateTypeId { get; set; }
        public int AggregateVersion { get; set; }
        
        public string EventTypeName { get; set; }
        public Guid EventTypeId { get; set; }
        public int EventVersion { get; set; }
        /// <summary>
        /// Gets or sets the event Creation Timestamp.
        /// </summary>
        /// <value>
        /// The event timestamp.
        /// </value>
        public DateTimeOffset EventTimestamp { get; set; }

        public object Payload { get; set; }
    }
}