namespace PDEventStore.Store.Persistence
{
    using System;

    /*
bucketId, (guid)
commitId, (guid)
aggrigateTypeName, (string(40))
aggrigateId, (guid)
aggrigateTypeId, (guid)
aggrigateVersion, (int)
aggrigateTypeId
aggrigateVersion, (int)
aggrigateData (blob/bytea)
timestamp      
     */
    public class SnapshotRecord
    {
        /// <summary>
        /// Gets or sets StoreRecord sequence. Generated by storage (read-only)
        /// </summary>
        /// <value>
        /// The sequence.
        /// </value>
        public int Sequence { get; set; }
        /// <summary>
        /// Gets or sets the Store Record timestamp.
        /// </summary>
        /// <value>
        /// The timestamp.
        /// </value>
        public DateTimeOffset Timestamp { get; set; }
        
        public string BucketId { get; set; }
        public Guid CommitId { get; set; }

        public Guid AggregateId { get; set; }
        public string AggregateTypeName { get; set; }
        public Guid AggregateTypeId { get; set; }
        public int AggregateVersion { get; set; }

        public object Payload { get; set; }
         
    }
}